name: instru_connect
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.3.2

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_messaging: ^16.0.1
  flutter_appauth: ^11.0.0
  intl: ^0.20.2
  firebase_storage: ^13.0.5
  file_picker: ^10.3.7
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  image_picker: ^1.2.1
  # google_sign_in: ^6.2.1

  # --- ADDED FOR EXCEL/CSV EXPORT ---
  csv: ^6.0.0
  share_plus: ^12.0.1
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/ic_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/ice1.jpeg
    - assets/logo/ic_logo.png
    - assets/PDF's/btech_timetable.pdf
    - assets/PDF's/sy_timetable.pdf
    - assets/PDF's/ty_timetable.pdf
